language: node_js
node_js:
- iojs
- '8'
deploy:
  provider: heroku
  api_key:
    secure: k6aZzFSa4vXF4Dpsu5zk+J+wluwc4SoBW3Bl7CbOYuw3rET3zmANfpws2UwM7W4/0hkywJJNb01tSEreetNdHgOpYq4AvFj5s3OPQLohfr2nDRyvGBy+WXSFn7kC3SDs3ObyuKRqHuQyLj08BH604aeASXPUg8uuvVlIxcQUH8N81Vi6drgMVDuVoIxEpBrd22Y73dFMsNtJszObpaNgE1ZIquML48IE8u4aaII/UUlYTSgYu7XJbfhVqCbxCNNeKO/JhGr910POIpydtEKJKoSO7zXAB6lWLWOUMUM/TG3fegDJ1oW35WW3oL7VSGtK6Hgigqo1KhQQ4lZkvqa0ngDw/+z+QrrNmO1qpE88bmp7AVVMKgtmWN6Hn8flmMXIfTD07AsiktE8bNM4GU2zTY3CR/+F/J9fJYjFyqfNaDxxPxO5C4xAdKHIfQbcTdbarS9wNe4QgLs/TeNiZ575HUvn9Snp6XFqg4/nUQ8eULelS6C1QAXPrKAJkbCCIj0ukNW4M65g7Bxs6JWBNokjdL3fNGLecWm4iPpl73PQqAuRwhyoAu15kWRqu3NCYGPbeHgopL/sKorouSk652ta+PwlzpMgLmVYuqMg6IizjH1jnghqCSJubuYhwFB8d14UqT9fj0Nicv9Lh7NDbBHjcEF1fIXqyfepP31vdm6TM2o=
  app: fullStack8
  on:
    repo: arjula075/fullStack8
